exclude: tests/test_payload.json
repos:
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
        args:
          - --application-directories=.:src:tests
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: [--safe, --quiet, --line-length, "100"]
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        language_version: python3
      - id: end-of-file-fixer
        language_version: python3
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        language_version: python3
        args:
          - --max-line-length=100
          - --ignore=W503,E203
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language_version: python3
        additional_dependencies:
          - types-requests
